# Generated by Django 3.2 on 2022-01-13 07:25

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenoms', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=25, verbose_name=django.forms.widgets.PasswordInput)),
                ('photo', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
