# Generated by Django 3.2 on 2022-01-13 07:27

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=255, verbose_name=django.forms.widgets.PasswordInput),
        ),
    ]
