# Generated by Django 3.2 on 2022-01-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjoutDeSejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcommande', models.CharField(max_length=255)),
                ('dureeenjour', models.IntegerField()),
                ('versementduclient', models.BooleanField(default=False)),
                ('dateajout', models.DateField(auto_now_add=True)),
                ('statudemande', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idclient', models.CharField(max_length=255)),
                ('idresidence', models.CharField(max_length=255)),
                ('prixactuel', models.IntegerField()),
                ('dateentree', models.DateField()),
                ('dureeenjour', models.IntegerField()),
                ('versementduclient', models.BooleanField(default=False)),
                ('cleauclient', models.BooleanField(default=False)),
                ('versementauproprio', models.BooleanField(default=False)),
                ('datecommande', models.DateField(auto_now_add=True)),
                ('statucommande', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NoteResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idclient', models.CharField(max_length=255)),
                ('idresidence', models.CharField(max_length=255)),
                ('note', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
