# Generated by Django 3.2 on 2022-01-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20220119_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
