# Generated by Django 3.2 on 2022-01-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20220121_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statucommande',
            field=models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], max_length=100),
        ),
    ]
