# Generated by Django 3.2 on 2022-01-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_commande_statucommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajoutdesejour',
            name='statudemande',
            field=models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], max_length=100),
        ),
    ]
