# Generated by Django 3.2 on 2022-01-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_ajoutdesejour_statudemande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteresidence',
            name='note',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (3, '4'), (5, '5')]),
        ),
    ]
