# Generated by Django 3.2 on 2022-01-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_noteresidence_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='dateentree',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='dureeenjour',
        ),
        migrations.AddField(
            model_name='commande',
            name='datedebut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='datefin',
            field=models.DateField(null=True),
        ),
    ]
