# version: "3"
   
# services:
#   db:
#     image: mysql
#     volumes:
#       - ./db_data_resi:/var/lib/mysql
#     restart: always  
#     environment:
#       MYSQL_ROOT_PASSWORD: Freedev2020@mysql
#       MYSQL_DATABASE: resi_db
#       MYSQL_USER: django
#   web:
#     build: .
#     command: gunicorn Resi_mysql.wsgi:application
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: root # database name
      MYSQL_ROOT_PASSWORD: Freedev2020@mysql # database password
    volumes:
      - ./production_mode/mysql/data/:/var/lib/mysql #Mount database data
      - ./production_mode/mysql/conf/my.cnf:/etc/mysql/my.cnf  #Mount profile
    ports:
      - "3307:3306"
    restart: always

  web:
    build: .
    expose:
      - "8000"
    volumes:
      - .:/code
      - /tmp/logs:/tmp
    command: bash start.sh
    links:
      - db
    depends_on:
      - db
    restart: always

  nginx:
    build: production_mode/nginx
    ports:
      - "81:80"
      - "443:443"
    expose:
      - "8000"
    volumes:
      - ./static:/usr/share/nginx/html/static # mount static files
    links:
      - web
    depends_on:
      - web
    restart: always