# Generated by Django 4.0.2 on 2022-03-27 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenoms', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(null=True, upload_to='proprio/image/profile/')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('user_id', models.IntegerField(null=True, unique=True)),
                ('password', models.TextField(max_length=255, null=True)),
                ('piece_identite', models.ImageField(null=True, upload_to='proprio/image/profile/')),
                ('isactivate', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbpieces', models.IntegerField()),
                ('descriptifresidence', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('prixjournalier', models.IntegerField()),
                ('disponibilité', models.BooleanField(default=True)),
                ('photocouverture', models.ImageField(null=True, upload_to='proprio/image/resi/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('idproprio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprio.proprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='Piecesresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nompiece', models.CharField(max_length=100)),
                ('idresidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprio.residence')),
            ],
        ),
        migrations.CreateModel(
            name='Imagepieceresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proprio/image/resi/')),
                ('idpiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprio.piecesresi')),
            ],
        ),
        migrations.CreateModel(
            name='Historiqueresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tempssurannonce', models.IntegerField()),
                ('visite3D', models.BooleanField(default=False)),
                ('residencecommandé', models.BooleanField(default=True)),
                ('idclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('idresidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprio.residence')),
            ],
        ),
    ]
