# Generated by Django 3.2 on 2022-01-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenoms', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=10)),
                ('username', models.CharField(default='root', max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='proprio/image/')),
            ],
        ),
    ]
