# Generated by Django 3.2 on 2022-01-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imageresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idresidence', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='proprio/image/resi/')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproprio', models.CharField(max_length=255)),
                ('descriptifresidence', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('prix', models.IntegerField(max_length=10)),
                ('disponibilité', models.BooleanField(default=True)),
            ],
        ),
    ]
