# Generated by Django 4.0.2 on 2022-02-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='isactivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='piece_identite',
            field=models.ImageField(null=True, upload_to='proprio/image/profile/'),
        ),
    ]
