# Generated by Django 3.2 on 2022-01-13 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proprio', '0002_imageresi_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresi',
            name='idresidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprio.residence'),
        ),
    ]
