# Generated by Django 3.2 on 2022-01-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprio', '0003_alter_imageresi_idresidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresi',
            name='idresidence',
            field=models.CharField(max_length=255),
        ),
    ]
