# Generated by Django 3.2 on 2022-01-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprio', '0004_alter_imageresi_idresidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historiqueresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('idresidence', models.CharField(max_length=255)),
                ('idclient', models.CharField(max_length=255)),
                ('duredesejour', models.IntegerField()),
                ('visite3D', models.BooleanField(default=False)),
                ('residencecommandé', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='residence',
            name='photocouverture',
            field=models.ImageField(null=True, upload_to='proprio/image/resi/'),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='residence',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
