# Generated by Django 3.2 on 2022-01-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprio', '0006_alter_proprietaire_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='photo',
            field=models.ImageField(null=True, upload_to='proprio/image/'),
        ),
    ]
