# Generated by Django 3.2 on 2022-01-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprio', '0007_alter_proprietaire_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiqueresi',
            old_name='duredesejour',
            new_name='tempssurannonce',
        ),
    ]
